peopleservice:
  data:
    # INMEMORY or DATABASE
    source: DATABASE

# only used when peopleservice.data.source = DATABASE

spring:
  application:
    name: peopleservice
  datasource:
    europe:
      url: jdbc:postgresql://localhost:15432/europe
      username: europe
      password: europe
      driver-class-name: org.postgresql.Driver
    america:
      url: jdbc:postgresql://localhost:25432/america
      username: america
      password: america
      driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false