peopleservice:
  data:
    # INMEMORY or DATABASE
    source: DATABASE
# peopleservice.datasource... properties are only used when peopleservice.data.source = DATABASE
  datasource:
    europe:
      url: jdbc:postgresql://localhost:15432/europe
      username: europe_user
      password: pw1
      driver-class-name: org.postgresql.Driver
    america:
      url: jdbc:postgresql://localhost:25432/america
      username: america
      password: america
      driver-class-name: org.postgresql.Driver


spring:
  application:
    name: peopleservice
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  port: 8081

togglz:
  console:
    enabled: true
    secured: false
  feature-enums: org.dummy.world.peopleservice.config.features.PeopleFeatures
logging:
  level:
    org.togglz: debug
    org.springframework.security: trace
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - mappings
          - togglz
